// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mufqqzlqofzekptoktra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11ZnFxemxxb2Z6ZWtwdG9rdHJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2Mzk5NzMsImV4cCI6MjA2NzIxNTk3M30.QamUMYUg4p_gHrZ42dZ6cfk4x4tC7ZuEZnEhWzlqo7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});